### PR TITLE
Use development vis server

### PR DESCRIPTION
**Pull request by jbeezley**
@mattben @sterlingbaldwin This branch should run with the dev server without any extra config.  Besides adding the static files [this](https://github.com/UV-CDAT/cdatweb/compare/dev-vis-server?expand=1#diff-91de90e4fc9c3f1bcd4ca16faaba3c5cR23) is the only config necessary in general.

Let me know if you have any problems.  Hopefully we won't DOS the server anytime soon :P.

### CODE REVIEW

**Comment by aashish24** [comment]
Lot of files it is :smile:

**Comment by aashish24** [comment]
@jbeezley does it mean that you don't have to build VTWeb ?

**Comment by jbeezley** [comment]
If you are using the development visualization server (and it hasn't crashed :stuck_out_tongue_winking_eye:) then you don't need to build UV-CDAT or VTKWeb.

**Comment by aashish24** [comment]
Nice :clap:

**Comment by mattben** [comment]
@jbeezley with this new configuration does it mean a user can choice and change there vis server connection by simply adding a VIS_SERVER = 'some-url' to the local_settings.py?

**Comment by jbeezley** [comment]
Yes, that was always the case from the front end perspective.  Configuring the vis server to work correctly is the complicated part.

**Pull request merged**
