### PR TITLE
Opendap authentication

### PR DESCRIPTION
**Pull request by jbeezley**
This exposes a method for logging into ESGF via an openid.  It requires the client to call something like this before opening a password protected file:

```javascript
session.call('cdat.esgf.logon', ['the open id url', 'the password'])
    .then(function (result) { /* result indicates success/failure */});
```

Exactly how this call occurs is still up in the air until we have a unified authentication API.  I will work on adding a temporary logon UI in my next pass through the client side code.

### CODE REVIEW

**Comment by mattben** [comment]
@jbeezley sorry I pulled straight in to master thus breaking your PR...

**Comment by mattben** [comment]
@jbeezley is this feature still going to make it in?

**Comment by jbeezley** [comment]
AFAIK, ESGF authentication still doesn't work in UV-CDAT.  If someone gives me a python script showing authentication working, I can integrate it.  Until then, there is not much I can do about it.

**Comment by mattben** [comment]
I'll get with @ sashakames and attempt to get one working.

**Pull request closed without merging**
