### PR TITLE
ENH: Print variable information for a nc file.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@jbeezley @mattben @aashish24 Please review. @mattben print_variables is function that prints variable information to the console. You can use this as a model to create a similar interface to uvcdat. Let me know if you have any questions or you need more info brought in.

**Comment by jbeezley** [comment]
The only issue I see is that you are trying to use block scoped variables, which don't currently exist in javascript.  All variables are in scope everywhere in the function they are declared.  ES6 has a [`let`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) keyword that does what you want, but would require transpiling to use in a browser.  It is generally [recommended](http://eslint.org/docs/rules/vars-on-top) to put `var` statements at the top of the functions.

**Comment by jbeezley** [comment]
That said, the JS here is just meant as an example of the RPC api.  The backend changes itself LGTM.

**Comment by danlipsa** [comment]
@jbeezley sounds good. I did know about the (ugly) scoping rules in JavaScript but did not know about this recommendation.

**Comment by danlipsa** [comment]
@chaosphere2112 @doutriaux1 Do we ever use 'generic grids' in uvcdat? Do we have a nc file with a generic grid?

**Comment by danlipsa** [comment]
@mattben I added printouts for all grid types: rectilinear, curvilinear and generic.

**Pull request merged**
