### PR TITLE
Add an alert to the plot window when rendering fails

### PR DESCRIPTION
**Pull request by jbeezley**

### CODE REVIEW

**Comment by mattben** [comment]
Do we care that the build failed?

**Comment by jbeezley** [comment]
The tests have been failing since September.  Some of the mocked calls to vcs need to be updated as well as fixing settings module in the test environment.  With my current commitments on other projects, it would take me several weeks before I can get it fixed.  To be honest, so little is actually tested here that I don't think that it really matters much.

**Comment by mattben** [comment]
sounds good. should we just kill the travis server then?

**Comment by jbeezley** [comment]
You can if you want.  Personally, I don't mind having in place as a persistent reminder.

**Pull request merged**
