### PR TITLE
Python flake8 tests and travis integration

### PR DESCRIPTION
**Pull request by jbeezley**

### CODE REVIEW

**Comment by mattben** [comment]
@jbeezley do you still want me to merge, or does it need to have travis pass first?

**Comment by jbeezley** [comment]
Let me fix it first.  I'll get to it shortly.

**Comment by jbeezley** [comment]
@mattben Fixed. 

Note, I also added `jscs` and `jshint` tests.

**Comment by jbeezley** [comment]
I'm going to be a rebel and merge this because it is just testing code.

@mattben You snooze, you loose.

**Comment by mattben** [comment]
:+1:

**Pull request merged**
